site_name: White paper on due diligence obligation of manufacturers
nav:
  - Chapter 1 - What is due diligence: 01.md
  - Chapter 2 - To what do we apply due diligence: 02.md
  - Chapter 3 - What and how to record due diligence, evidence: 03.md
  - Chapter 4 - What happens when due diligence fails: 04.md
  - Chapter 5 - How open source projects and stewards can help manufacturers to achieve due diligence: 05.md
  - Chapter 6 - Additional aspects/references: 06.md

docs_dir: content
site_author: Eclipse Foundation | ORC WG | Cyber Resilience SIG
site_description: >-
  White paper on due diligence obligation of manufacturers by the Cyber Resilience SIG of ORC WG
# repository
repo_name: orcwg/cra-due-diligence
repo_url: https://github.com/orcwg/cra-due-diligence
site_url: "https://docs.sdcio.dev"
theme:
  name: material
  #custom_dir: docs/overrides
  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  language: en
  features:
    - navigation.left
    - navigation.instant
    - navigation.tracking
#    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.sections
#    - navigation.tabs.sticky
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.tooltips
    #- header.autohide
    #- search.highlight
    #- search.share
    #- search.suggest
    #- toc.integrate
    - toc.follow
    
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Manrope
    code: Fira Mono
  icon:
    logo: fontawesome/solid/sitemap
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  favicon: https://avatars.githubusercontent.com/u/189788385?s=48&v=4
  logo: https://avatars.githubusercontent.com/u/189788385?s=48&v=4


# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  
# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/orcwg/cra-due-diligence
    # - icon: fontawesome/brands/discord
    #   link: https://discord.gg/fHCNahWR2T
  version:
    provider: mike
    
extra_css:
  - stylesheets/extra.css

# hooks
#hooks:
#  - hooks/copy.py

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      line_spans: __span
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
#  - pymdownx.magiclink:
#      repo_url_shorthand: true
#      user: sdcio
#      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.snippets:
      check_paths: true
      #dedent_subsections: true
      base_path:
        - ./
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

